using System;using System.IO;using System.Linq;using System.Drawing;using System.Drawing.Printing;using System.Text;using System.Text.Json;
record Request(string command,PrintJob? job);record PrintJob(string printer,int copies,string imageDataUrl,int dpi);record Reply(bool ok,string? message=null,object? printers=null,object? details=null);
static class App{
 static readonly JsonSerializerOptions Json=new(){PropertyNameCaseInsensitive=true};
 static byte[] Read(){var s=Console.OpenStandardInput();Span<byte> n=stackalloc byte[4];if(s.Read(n)!=4)return[];var len=BitConverter.ToInt32(n);var b=new byte[len];for(int p=0;p<len;){var r=s.Read(b,p,len-p);if(r==0)break;p+=r;}return b;}
 static void Write(object value){var b=JsonSerializer.SerializeToUtf8Bytes(value,Json);var o=Console.OpenStandardOutput();o.Write(BitConverter.GetBytes(b.Length));o.Write(b);o.Flush();}
 static Reply Diagnose(){var printers=PrinterSettings.InstalledPrinters.Cast<string>().ToArray();var idp=printers.Where(x=>x.Contains("IDP",StringComparison.OrdinalIgnoreCase)||x.Contains("SMART",StringComparison.OrdinalIgnoreCase)).ToArray();var smartComm=Directory.GetFiles(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),"SmartComm2.dll",SearchOption.AllDirectories).Take(10).ToArray();return new(true,printers:printers,details:new{recommended=idp,smartComm,os=Environment.OSVersion.ToString()});}
 static Reply Print(PrintJob j){if(string.IsNullOrWhiteSpace(j.printer))return new(false,"Принтер не выбран в настройках.");var raw=j.imageDataUrl[(j.imageDataUrl.IndexOf(',')+1)..];var bytes=Convert.FromBase64String(raw);using var ms=new MemoryStream(bytes);using var image=Image.FromStream(ms);using var doc=new PrintDocument();doc.PrinterSettings.PrinterName=j.printer;doc.PrinterSettings.Copies=(short)Math.Clamp(j.copies,1,10);if(!doc.PrinterSettings.IsValid)return new(false,$"Принтер «{j.printer}» не найден.");doc.DefaultPageSettings.Landscape=true;doc.DefaultPageSettings.Margins=new Margins(0,0,0,0);doc.PrintPage+=(_,e)=>{e.Graphics!.PageUnit=GraphicsUnit.Display;e.Graphics.DrawImage(image,new Rectangle(0,0,337,213));e.HasMorePages=false;};doc.Print();return new(true,"Задание отправлено.");}
 public static void Main(){try{var b=Read();if(b.Length==0)return;var r=JsonSerializer.Deserialize<Request>(b,Json)!;Write(r.command switch{"diagnose"=>Diagnose(),"ping"=>new Reply(true,"connected"),"print" when r.job is not null=>Print(r.job),_=>new Reply(false,"Неизвестная команда.")});}catch(Exception e){Write(new Reply(false,"Ошибка локальной печати.",details:e.ToString()));}}
}
